import express from "express";
import helmet from "helmet";
import cors from "cors";
import hpp from "hpp";
import { corsOptions } from "@config/cors.origins";
import { errorHandler, notFoundHandler } from "@lib/middlewares/errorHandler";
import { authRouter } from "@routes";
export const app = express();
app.set("trust proxy", 1);
app.use(helmet());
app.use(cors(corsOptions));
app.use(express.json({ limit: "10kb" }));
app.use(express.urlencoded({ extended: false }));
app.use(hpp());
app.use("/api/v1/auth", authRouter);
app.use(notFoundHandler);
app.use(errorHandler);
